
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[override]]
 name = "github.com/cloudfoundry/socks5-proxy"
 revision = "3c6b4eec9c2d16c1dac4c42bdb5f755ba09daff8"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-incubator/cf-test-helpers"

[[constraint]]
  name = "github.com/cloudfoundry/noaa"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/sonde-go"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/craigfurman/herottp"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  version = "^6.0.0"

[[constraint]]
  name = "github.com/pivotal-cf/on-demand-services-sdk"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/totherme/unstructured"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-cli"
  version = "3.0.1"

[[override]]
  name = "github.com/cheggaaa/pb"
  version = "=1.0.18"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  name = "code.cloudfoundry.org/credhub-cli"
  branch = "master"
