# Copyright (C) 2016-Present Pivotal Software, Inc. All rights reserved.
# This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

---
broker:
  port: 8080
  username: username
  password: password
credhub:
    # api_url: example.com
    client_id: myclient
    client_secret: mysecret
service_adapter:
  path: test_assets/executable.sh
service_deployment:
  releases: []
  stemcell: {}
bosh:
  url: "a-url"
  authentication:
    uaa:
      url: http://some-uaa-server:99
      client_id: some-client-id
      client_secret: some-client-secret
cf:
  url: some-cf-url
  root_ca_cert: some-cf-cert
  authentication:
    url: a-uaa-url
    user_credentials:
      username: some-cf-username
      password: some-cf-password
service_catalog:
  id: some-id
  service_name: some-marketplace-name
  service_description: some-description
  bindable: true
  plan_updatable: true
  metadata: {}
  tags: []
  plans: []
